### CONSTANTS
@URI = http://localhost:8080/login
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRlIjoxNjEyMTM1MTgxNzUwLCJfaWQiOiI2MDE0Y2Y0Zjc1ZmZhZjRlNjA2YTYwYmQiLCJwcm9maWxlIjp7fSwiaWF0IjoxNjEyMTM1MTgxfQ.N4lfzmwDIs6eCNIagkt-M9glajDpbYD01UiovuUREy0

### LogIn
POST {{URI}} HTTP/1.1
Content-Type: application/json

{
	"cpf": "123",
	"dataAccess": {"password": "123"}
}

### LogOff
POST {{URI}}/logoff HTTP/1.1
Content-Type: application/json
authorization: {{TOKEN}}

### LogOn
POST {{URI}}/logon HTTP/1.1
Content-Type: application/json
authorization: {{TOKEN}}

{
	"dataAccess": {"password": "123"}
}

### LogOut
POST {{URI}}/logout HTTP/1.1
Content-Type: application/json
authorization: {{TOKEN}}
